"use client";
import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import { getHederaWalletState, sendHederaWalletTransaction, subscribeHederaAuth, type HederaAuthState, type HederaWalletTransaction } from "../lib/hedera-wallet";
import { formatMoney, transactionLink } from "../lib/api-client";
import { issuanceRequest } from "./issuance-dialog";
import { useWorkspace } from "./workspace-provider";
import styles from "./workspace.module.css";

interface Quote { quoteId: string; units: string; amountMinorUnits: string; state: string; prepared: HederaWalletTransaction; transactionId?: string | null; expiresAt: string; error?: string | null }
interface FinancingView { financingId: string; name: string; state: string; enabled: boolean; unitPriceMinorUnits: string; totalUnits: string; retainedUnits: string; subscriptionUnits: string; cashRequiredMinorUnits: string; paidUnits: string; paidAmountMinorUnits: string; availableUnits: string; tokenId: string; escrowAddress: string; assignment?: { mode: string; hash: string; documentJson: string | null; legalEffect: string }; lastError?: string; quotes: Quote[]; steps: { kind: string; state: string; transactionId?: string }[] }
const stageName: Record<string, string> = { PAY_ORIGINATOR: "Pay purchase consideration", ALLOCATE_RETAINED: "Allocate same-class retained units", ALLOCATE_INVESTOR: "Allocate paid investor units", CREATE_POOL: "Commit approved pool", DEPLOY_PAYOUT: "Create dedicated payout contract", ACTIVATE_POOL: "Activate Registry pool", INITIALIZE_PAYOUT: "Confirm payment token association" };

export function OpenFinancingButton({ issuanceId }: { issuanceId: string }) {
  const key = useRef<string | null>(null); const [financingId, setFinancingId] = useState<string>(); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [auth, setAuth] = useState<HederaAuthState>(); useEffect(() => subscribeHederaAuth(setAuth), []);
  return <><button type="button" className={styles.primaryButton} disabled={busy || !auth?.roles.includes("issuer")} onClick={async () => { setBusy(true); setError(""); try { key.current ??= crypto.randomUUID(); const result = await issuanceRequest<{ financingId: string }>(`/api/issuances/${issuanceId}/financing`, {}, key.current); setFinancingId(result.financingId); } catch (reason) { setError(reason instanceof Error ? reason.message : "Subscriptions could not be opened."); } finally { setBusy(false); } }}>{busy ? "Checking settlement setup…" : "Open subscriptions"}</button>{error && <p role="alert">{error}</p>}{financingId && <FinancingPanel financingId={financingId} />}</>;
}
export function FinancingWorkspace() {
  const [auth, setAuth] = useState<HederaAuthState>(); const [items, setItems] = useState<{ financingId: string; name: string; state: string }[]>([]); const [selected, setSelected] = useState(""); const [error, setError] = useState("");
  useEffect(() => subscribeHederaAuth(setAuth), []);
  const actor = auth?.accountId;
  const updateProgress = useCallback((next: Pick<FinancingView, "financingId" | "name" | "state">) => {
    setItems(previous => previous.some(item => item.financingId === next.financingId && (item.state !== next.state || item.name !== next.name))
      ? previous.map(item => item.financingId === next.financingId ? { financingId: next.financingId, name: next.name, state: next.state } : item)
      : previous);
  }, []);
  useEffect(() => { if (!actor) return; let disposed = false; void issuanceRequest<{ financings: typeof items }>("/api/financings").then(result => { if (!disposed) { setItems(result.financings); setSelected(previous => previous || (result.financings.length === 1 ? result.financings[0]!.financingId : "")); setError(""); } }).catch(reason => { if (!disposed) setError(reason instanceof Error ? reason.message : "Subscriptions unavailable."); }); return () => { disposed = true; }; }, [actor]);
  return <section className={styles.panel}><div className={styles.panelHeader}><h2>Primary subscriptions</h2></div><div className={styles.panelBody}>{!auth ? <p>Sign in to review offered units and your saved payment requests.</p> : <>{error && <p role="alert">{error}</p>}{items.length === 0 && !error && <p>No workspace issuance is currently open for subscription.</p>}{items.length > 0 && <label className={styles.fullField}><span>Financing</span><select value={selected} onChange={event => setSelected(event.target.value)}><option value="">Choose a financing</option>{items.map(item => <option key={item.financingId} value={item.financingId}>{item.name} · {item.state}</option>)}</select></label>}{selected && <FinancingPanel key={`${actor}:${selected}`} financingId={selected} onProgress={updateProgress} />}</>}</div></section>;
}
export function FinancingPanel({ financingId, onProgress }: { financingId: string; onProgress?: (view: Pick<FinancingView, "financingId" | "name" | "state">) => void }) {
  const { refresh: refreshWorkspace } = useWorkspace();
  const [auth, setAuth] = useState<HederaAuthState>(); const [view, setView] = useState<FinancingView>(); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [knownHash, setKnownHash] = useState("");
  const key = useRef<{ fingerprint: string; value: string } | null>(null);
  useEffect(() => subscribeHederaAuth(setAuth), []);
  const refresh = useCallback(async () => { const next = await issuanceRequest<FinancingView>(`/api/financings/${financingId}`); setView(next); onProgress?.(next); }, [financingId, onProgress]);
  const actor = auth?.accountId;
  const financingState = view?.state;
  useEffect(() => { if (financingState === "ACTIVE") void refreshWorkspace(); }, [financingState, refreshWorkspace]);
  useEffect(() => { if (!actor) return; let disposed = false; const update = async () => { try { const next = await issuanceRequest<FinancingView>(`/api/financings/${financingId}`); if (!disposed) { setView(next); onProgress?.(next); } } catch (reason) { if (!disposed) setError(reason instanceof Error ? reason.message : "Financing progress unavailable."); } }; void update(); const timer = setInterval(() => void update(), 3000); return () => { disposed = true; clearInterval(timer); }; }, [financingId, actor, onProgress]);
  const run = async (work: () => Promise<void>) => { if (busy) return; setBusy(true); setError(""); try { await work(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Request could not be completed."); } finally { setBusy(false); } };
  const quote = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); event.stopPropagation(); const units = String(new FormData(event.currentTarget).get("units")); await run(async () => { const body = { units }; const fingerprint = JSON.stringify(body); if (key.current?.fingerprint !== fingerprint) key.current = { fingerprint, value: crypto.randomUUID() }; await issuanceRequest(`/api/financings/${financingId}/quotes`, body, key.current.value); key.current = null; await refresh(); }); };
  const pay = (quote: Quote) => void run(async () => {
    if (!auth) throw new Error("Sign in before approving payment.");
    const wallet = getHederaWalletState(); if (wallet.accountId !== auth.accountId || !wallet.walletKind) throw new Error("Connected wallet must match the authenticated investor.");
    const started = await issuanceRequest<Quote>(`/api/subscriptions/${quote.quoteId}/signing`, { walletKind: wallet.walletKind });
    setView(previous => previous ? { ...previous, quotes: previous.quotes.map(item => item.quoteId === started.quoteId ? started : item) } : previous);
    try { const transactionId = await sendHederaWalletTransaction(started.prepared, auth.accountId); setKnownHash(transactionId); await issuanceRequest(`/api/subscriptions/${quote.quoteId}/receipt`, { transactionId }); }
    catch (reason) { throw new Error(`${reason instanceof Error ? reason.message : "Wallet response unavailable."} The saved payment remains unresolved. Reconcile its original transaction before any new approval.`); }
    await refresh();
  });
  const openQuote = view?.quotes.some(item => ["QUOTED", "WALLET_PENDING", "PAYMENT_PENDING", "REVIEW_REQUIRED"].includes(item.state));
  return <section aria-label="Subscription and settlement progress"><h3>{view?.name ?? "Loading financing…"}</h3>{view && <>
    <p>{view.state === "ACTIVE" ? "Financing settled and pool activated" : view.state === "SETTLING" ? "Payments confirmed · Settlement in progress" : view.state === "BLOCKED" ? "Settlement requires reconciliation" : "Subscriptions open"}</p>
    {view.assignment && <details><summary>Assignment commitment</summary><p className={styles.helpText}>{view.assignment.mode === "SYNTHETIC_REVIEWED_POOL" ? "Synthetic test artifact · NO LEGAL EFFECT. Applies only to this run's reviewed roots and terms." : "Externally supplied document hash. Authenticity and legal effect are not verified by this application."}</p><code style={{ overflowWrap: "anywhere" }}>{view.assignment.hash}</code>{view.assignment.documentJson && <pre style={{ whiteSpace: "pre-wrap", overflowWrap: "anywhere" }}>{view.assignment.documentJson}</pre>}</details>}
    <div className={styles.reviewLine}><span>Paid subscriptions</span><strong>{view.paidUnits} / {view.subscriptionUnits} units</strong></div><div className={styles.reviewLine}><span>Verified payments</span><strong>{formatMoney(view.paidAmountMinorUnits)} / {formatMoney(view.cashRequiredMinorUnits)}</strong></div><div className={styles.reviewLine}><span>Originator retention</span><strong>{view.retainedUnits} of {view.totalUnits} identical units · 5%</strong></div>
    {view.state === "SUBSCRIBING" && <form onSubmit={quote}><div className={styles.formGrid}><label><span>Units to subscribe</span><input name="units" required inputMode="numeric" pattern="[1-9][0-9]*" maxLength={18} /><small>{formatMoney(view.unitPriceMinorUnits)} per unit · {view.availableUnits} unreserved units</small></label></div><button className={styles.primaryButton} disabled={busy || !view.enabled || !auth?.roles.includes("investor") || openQuote}>{busy ? "Preparing quote…" : "Get payment quote"}</button>{!auth?.roles.includes("investor") && <p className={styles.helpText}>An assigned investor must sign in and have current ATS KYC.</p>}</form>}
    {view.quotes.map(item => <section key={item.quoteId} aria-label={`Subscription ${item.units} units`}><h4>{item.units} units · {formatMoney(item.amountMinorUnits)}</h4><p>{item.state.replaceAll("_", " ")}</p>{item.state === "QUOTED" && <><p className={styles.helpText}>Your wallet pays token {view.tokenId} to the dedicated escrow. Review the recipient and amount before approval.</p><details><summary>Payment recipient</summary><code style={{ overflowWrap: "anywhere" }}>{view.escrowAddress}</code></details><button type="button" className={styles.primaryButton} disabled={busy || !view.enabled} onClick={() => pay(item)}>Approve payment in wallet</button><button type="button" className={styles.secondaryButton} disabled={busy} onClick={() => void run(async () => { await issuanceRequest(`/api/subscriptions/${item.quoteId}/cancel`, {}); await refresh(); })}>Cancel unapproved quote</button></>}{item.state === "WALLET_PENDING" && !item.transactionId && <form onSubmit={event => { event.preventDefault(); event.stopPropagation(); void run(async () => { await issuanceRequest(`/api/subscriptions/${item.quoteId}/receipt`, { transactionId: knownHash }); await refresh(); }); }}><p>A wallet request started. If its response was lost, recover the original transaction hash from your wallet; a second approval is disabled.</p><div className={styles.formGrid}><label className={styles.fullField}><span>Original payment transaction hash</span><input required value={knownHash} onChange={event => setKnownHash(event.target.value)} /></label></div><button className={styles.secondaryButton} disabled={busy}>Reconcile original payment</button></form>}{item.transactionId && transactionLink(item.transactionId) && <a href={transactionLink(item.transactionId)} target="_blank" rel="noreferrer">Payment receipt</a>}{item.error && <p role="alert">{item.error}</p>}{item.state === "PAID" && view.state !== "ACTIVE" && <p className={styles.helpText}>Payment is verified. Allocation completes only after the full subscription requirement is funded and settlement succeeds.</p>}</section>)}
    {view.steps.length > 0 && <details open><summary>Settlement stages</summary>{view.steps.map((step, index) => <div className={`${styles.reviewLine} ${styles.financingStage}`} key={index}><span>{stageName[step.kind] ?? step.kind}</span><strong>{step.state}</strong>{step.transactionId && transactionLink(step.transactionId) && <a href={transactionLink(step.transactionId)} target="_blank" rel="noreferrer">Receipt</a>}</div>)}</details>}
    {view.lastError && <p role="alert">{view.lastError}</p>}<p className={styles.helpText}>Hedera testnet settlement uses INRx-equivalent tokens. Payments, originator consideration and allocations occur in a controlled sequence, not atomic delivery-versus-payment. Incomplete subscriptions or failed settlement require explicit reconciliation; refunds are not automatic.</p>
  </>}{error && <p className={styles.formError} role="alert">{error}</p>}</section>;
}
