import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import Fastify from "fastify";
import pg from "pg";
import { id } from "ethers";
import { beforeAll, afterAll, test, expect } from "vitest";
import { registerDistributions } from "../src/distributions.js";
import { distributionPreview } from "@receivablex/domain";
const connectionString = process.env.DATABASE_URL ?? "postgresql://receivablex:receivablex@localhost:5432/receivablex";
const admin = new pg.Pool({ connectionString });
const schema = `distribution_api_${randomUUID().replaceAll("-", "")}`;
const db = new pg.Pool({ connectionString, options: `-c search_path=${schema}` });
const poolId = id("distribution-api-pool");
const account = "0.0.111";
const session = async () => ({ sessionId: "test", accountId: account, roles: ["trustee"], expiresAt: new Date(Date.now() + 100_000).toISOString() });
const app = Fastify();
beforeAll(async () => {
  await admin.query(`create schema ${schema}`);
  for (const file of ["001_initial.sql", "002_operations.sql", "005_pool_isolation.sql", "008_distributions_workflow.sql", "011_payout_attempts.sql"]) await db.query(await readFile(new URL(`../../db/migrations/${file}`, import.meta.url), "utf8"));
  await db.query("insert into pools(pool_id,pool_root,eligibility_root,manifest_hash,original_face,performing_face,principal_outstanding,available_cash,state,chain_id,security_address,payout_address,registry_address,projection_as_of,projection_metadata) values($1,$1,$1,$1,1000,1000,900,1000,'ACTIVE',296,$2,$3,$4,now(),'{\"distributionVersion\":3}')", [poolId, `0x${"1".repeat(40)}`, `0x${"2".repeat(40)}`, `0x${"3".repeat(40)}`]);
  registerDistributions(app, db, session, { enabled: true, trusteeAccountId: account });
});
afterAll(async () => { await app.close(); await db.end(); await admin.query(`drop schema ${schema} cascade`); await admin.end(); });
test("authenticated snapshot request is durable, idempotent and occupies the shared pool gate", async () => {
  await db.query("update pools set state='MATURED'");
  const request = { method: "POST" as const, url: `/api/pools/${poolId}/distributions`, headers: { "idempotency-key": "distribution-api-001" }, payload: { amountMinorUnits: "100", expectedStateVersion: "0" } };
  await db.query("update pools set projection_metadata='{\"distributionVersion\":2}'");
  expect((await app.inject(request)).statusCode).toBe(503);
  expect((await db.query("select count(*)::int as count from chain_operations")).rows[0].count).toBe(0);
  await db.query("update pools set projection_metadata='{\"distributionVersion\":3}'");
  const first = await app.inject(request);
  expect(first.statusCode).toBe(202);
  const replay = await app.inject(request);
  expect(replay.statusCode).toBe(202); expect(replay.json().distributionId).toBe(first.json().distributionId);
  expect((await db.query("select count(*)::int as count from distribution_steps")).rows[0].count).toBe(1);
  expect((await app.inject({ ...request, payload: { ...request.payload, amountMinorUnits: "99" } })).statusCode).toBe(409);
  expect((await app.inject({ ...request, headers: { "idempotency-key": "distribution-api-002" }, payload: { ...request.payload, expectedStateVersion: "1" } })).statusCode).toBe(409);
  const preview = distributionPreview(1n, { holders: [{ address: `0x${"4".repeat(40)}`, balance: 1n }], snapshotSupply: 1n, principalBudget: 100n, incomeBudget: 0n });
  await db.query("update distribution_workflows set state='PREVIEW',preview=$1", [preview]);
  const approve = { method: "POST" as const, url: `/api/distributions/${first.json().distributionId}/approve`, payload: { previewHash: preview.previewHash } };
  expect((await app.inject({ ...approve, payload: { previewHash: id("tampered") } })).statusCode).toBe(409);
  expect((await app.inject(approve)).statusCode).toBe(202);
  expect((await app.inject(approve)).json().replayed).toBe(true);
  await expect(db.query("update distribution_workflows set preview=$1", [{ ...preview, principalBudget: "99" }])).rejects.toThrow("immutable");
  expect((await db.query("select count(*)::int as count from distribution_steps where kind='APPROVE'")).rows[0].count).toBe(1);
  expect((await app.inject({ url: `/api/distributions/${first.json().distributionId}` })).json().state).toBe("APPROVING");
  expect((await app.inject({ url: `/api/pools/${poolId}/distributions` })).json()).toEqual([{ distributionId: first.json().distributionId, state: "APPROVING" }]);
});
test("default feature gate and trustee identity fail closed", async () => {
  const disabled = Fastify(); registerDistributions(disabled, db, session, { enabled: false });
  expect((await disabled.inject({ method: "POST", url: `/api/pools/${poolId}/distributions`, payload: {} })).statusCode).toBe(503);
  await disabled.close();
  const unauthorized = Fastify(); registerDistributions(unauthorized, db, async (_request, reply) => { reply.code(401).send({ error: "Sign in" }); return undefined; }, { enabled: true });
  expect((await unauthorized.inject({ method: "POST", url: `/api/pools/${poolId}/distributions`, payload: {} })).statusCode).toBe(401);
  await unauthorized.close();
});
