import { afterAll, beforeAll, expect, test } from "vitest";
import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import Fastify from "fastify";
import pg from "pg";
import { id } from "ethers";
import { createPool } from "@receivablex/db";
import type { LifecycleTransport } from "@receivablex/hedera-native";
import { registerLifecycle } from "../../api/src/lifecycle.js";
import { processLifecycleOne } from "../src/lifecycle-processor.js";
const admin = createPool(); const schema = `lifecycle_${randomUUID().replaceAll("-", "")}`;
const database = new pg.Pool({ connectionString: process.env.DATABASE_URL ?? "postgresql://receivablex:receivablex@localhost:5432/receivablex", options: `-c search_path=${schema}` });
const app = Fastify(); const poolId = id("lifecycle-test"); let accountId = "0.0.123"; let roles = ["trustee"];
const savedGate = process.env.LIFECYCLE_COMMANDS_ENABLED, savedTrustee = process.env.HEDERA_TRUSTEE_ACCOUNT_ID;
beforeAll(async () => {
  await admin.query(`create schema ${schema}`);
  for (const file of ["001_initial.sql", "002_operations.sql", "010_lifecycle.sql"]) await database.query(await readFile(new URL(`../../db/migrations/${file}`, import.meta.url), "utf8"));
  await database.query("insert into pools(pool_id,pool_root,eligibility_root,manifest_hash,original_face,performing_face,principal_outstanding,state,projection_as_of,projection_metadata,registry_address,security_address) values($1,$1,$1,$1,100,0,0,'ACTIVE',now(),'{\"lifecycleVersion\":1,\"maturity\":\"1\",\"pendingDistributions\":\"0\"}',$2,$2)", [poolId, "0x" + "12".repeat(20)]);
  registerLifecycle(app, database, async (_req, reply, role) => { if (role && !roles.includes(role)) { reply.code(403).send({ error: "role" }); return; } return { accountId, roles, sessionId: "session", expiresAt: new Date(Date.now() + 60000).toISOString() }; });
  process.env.LIFECYCLE_COMMANDS_ENABLED = "true"; process.env.HEDERA_TRUSTEE_ACCOUNT_ID = accountId;
});
afterAll(async () => { if (savedGate === undefined) delete process.env.LIFECYCLE_COMMANDS_ENABLED; else process.env.LIFECYCLE_COMMANDS_ENABLED = savedGate; if (savedTrustee === undefined) delete process.env.HEDERA_TRUSTEE_ACCOUNT_ID; else process.env.HEDERA_TRUSTEE_ACCOUNT_ID = savedTrustee; await app.close(); await database.end(); await admin.query(`drop schema ${schema} cascade`); await admin.end(); });
const post = (action: string, version: string, key: string) => app.inject({ method: "POST", url: `/api/pools/${poolId}/lifecycle`, headers: { "idempotency-key": key }, payload: { action, expectedStateVersion: version, amountUnits: action === "RETIRE" ? "50" : "0" } });
const prepared = { from: "0x" + "34".repeat(20), to: "0x" + "12".repeat(20), data: "0x12345678", value: "0x0" as const, chainId: "0x128" as const, gas: "0x123", nonce: "0x0" };
test("maturity is role/date/capability gated and durable signed bytes survive ambiguous submission", async () => {
  roles = []; expect((await post("MATURE", "0", "maturity-key")).statusCode).toBe(403); roles = ["trustee"];
  process.env.LIFECYCLE_COMMANDS_ENABLED = "false"; expect((await post("MATURE", "0", "maturity-key")).statusCode).toBe(503); process.env.LIFECYCLE_COMMANDS_ENABLED = "true";
  await database.query("update pools set projection_metadata=jsonb_set(projection_metadata,'{maturity}',to_jsonb('9999999999'::text))"); expect((await post("MATURE", "0", "maturity-key")).statusCode).toBe(422); await database.query("update pools set projection_metadata=jsonb_set(projection_metadata,'{maturity}',to_jsonb('1'::text))");
  const response = await post("MATURE", "0", "maturity-key"); expect(response.statusCode).toBe(202);
  expect((await post("MATURE", "0", "maturity-key")).json().operationId).toBe(response.json().operationId);
  let count = 0, sends = 0, confirmed = false;
  const bytes = Buffer.from("signed-maturity");
  const transport: LifecycleTransport = { prepare: async () => { count++; return { prepared, signedBytes: bytes, transactionId: id("maturity") }; }, submit: async value => { sends++; expect(Buffer.from(value)).toEqual(bytes); expect((await database.query("select signed_bytes from lifecycle_requests")).rows[0].signed_bytes).toEqual(bytes); }, reconcile: async () => confirmed ? { success: true, status: "SUCCESS" } : null };
  await processLifecycleOne(database, transport, async () => ""); await database.query("update chain_operations set next_attempt_at=now()"); await processLifecycleOne(database, transport, async () => ""); expect(count).toBe(1); expect(sends).toBe(2);
  confirmed = true; await database.query("update chain_operations set next_attempt_at=now()"); await processLifecycleOne(database, transport, async () => { await database.query("update pools set state='MATURED'"); return ""; });
  expect((await database.query("select state from lifecycle_requests")).rows[0].state).toBe("CONFIRMED");
});
test("holder ownership and pre-wallet state stop duplicate approval; native ID reconciles even with lost wallet response", async () => {
  accountId = "0.0.456"; roles = ["investor"];
  const response = await post("RETIRE", "1", "retire-key"); expect(response.statusCode).toBe(202); const operationId = response.json().operationId;
  const nativeId = "0.0.456@100.000000001";
  let prepares = 0, confirmed = false;
  const transport: LifecycleTransport = { prepare: async context => { prepares++; expect(context.actorAccountId).toBe("0.0.456"); return { prepared: { ...prepared, holderAccountId: accountId, nativeTransactionId: nativeId, nativeTransactionList: "bytes", nativeValidUntil: new Date(Date.now() + 120000).toISOString() }, signedBytes: null, transactionId: null }; }, submit: async () => { throw new Error("Never broadcast a holder transaction from server"); }, reconcile: async (_context, transactionId) => { expect(transactionId).toBe(nativeId); return confirmed ? { success: true, status: "SUCCESS" } : null; } };
  await processLifecycleOne(database, transport, async () => "");
  const path = `/api/lifecycle/${operationId}`;
  accountId = "0.0.789"; expect((await app.inject({ method: "GET", url: path })).statusCode).toBe(404); expect((await app.inject({ method: "POST", url: `${path}/signing`, payload: { walletKind: "native" } })).statusCode).toBe(409);
  accountId = "0.0.456";
  expect((await app.inject({ method: "POST", url: `${path}/signing`, payload: { walletKind: "native" } })).statusCode).toBe(200);
  expect((await app.inject({ method: "POST", url: `${path}/signing`, payload: { walletKind: "native" } })).statusCode).toBe(409);
  expect((await database.query("select transaction_id from lifecycle_requests where operation_id=$1", [operationId])).rows[0].transaction_id).toBe(nativeId);
  await processLifecycleOne(database, transport, async () => ""); expect(prepares).toBe(1);
  confirmed = true; await database.query("update chain_operations set next_attempt_at=now()"); await processLifecycleOne(database, transport, async () => "");
  expect((await app.inject({ method: "GET", url: path })).json().state).toBe("CONFIRMED");
});
